name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repository
        uses: actions/checkout@v4

      - name: Setup di Java (JDK 17 LTS)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup di SBT
        uses: sbt/setup-sbt@v1

      - name: Esecuzione compilazione e test
        run: sbt clean test